
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'discount_value_model.freezed.dart';

// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'discount_value_model.g.dart';

@freezed
class DiscountValueModel with _$DiscountValueModel {
  const factory DiscountValueModel({
    required num discount_value_price,
    required num final_price,

  }) = _DiscountValue;

  factory DiscountValueModel.fromJson(Map<String, Object?> json)
  => _$DiscountValueModelFromJson(json);
}


