
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'package_model.freezed.dart';

// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'package_model.g.dart';
enum PlanType { exercise, diet, both }

@freezed
class PackageModel with _$PackageModel {
const factory PackageModel({
required int id,
required String name,
required int duration,
required String price,
required PlanType type,
required int is_active,
required String? image,
// required String? recaptcha_token,


}) = _Package;

factory PackageModel.fromJson(Map<String, Object?> json)
=> _$PackageModelFromJson(json);
}

