// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUQO-_TDZGmw6cKg6TFxRI4L43njikgN8',
    appId: '1:916677939315:android:0370383a365084438bda06',
    messagingSenderId: '916677939315',
    projectId: 'urfit-b2d73',
    storageBucket: 'urfit-b2d73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsZRyxVenznXFejo2-AJRO4e1S6H46Np0',
    appId: '1:916677939315:ios:72fb7ad4b5ec90bf8bda06',
    messagingSenderId: '916677939315',
    projectId: 'urfit-b2d73',
    storageBucket: 'urfit-b2d73.firebasestorage.app',
    androidClientId: '916677939315-5k2sqnmr9decjlk88oskr352kk274t4d.apps.googleusercontent.com',
    iosClientId: '916677939315-tsq1iqpkh8i3r767lbvtv4ntdisegdd6.apps.googleusercontent.com',
    iosBundleId: 'com.rmz.urfit',
  );

}