import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'user_features_model.freezed.dart';

// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'user_features_model.g.dart';

@freezed
class UserFeaturesModel with _$UserFeaturesModel {
  const factory UserFeaturesModel({

    required bool? search_results_table,
    required bool? recently_opened_files,

    required bool? search_history,
    required bool? highlights_and_notes,

    required bool? gpt,
    required bool? my_folders,
    required bool? contracts,


  }) = _UserFeatures;

  factory UserFeaturesModel.fromJson(Map<String, Object?> json)
  => _$UserFeaturesModelFromJson(json);
}

